### PR TITLE
Update maven to version 3.6.2.

### PR DESCRIPTION
**Pull request by Firefishy**
Update to maven 3.6.2 (latest)

### CODE REVIEW

**Comment by Firefishy** [comment]
@arianna could you review?

**Comment by Firefishy** [comment]
@karianna Please could you review.

**Comment by Firefishy** [comment]
@dinogun Please could you review.

**Review by karianna — APPROVED** [review]
LGTM

**Comment by dinogun** [comment]
Thanks for the PR, the images should now be updated.

**Pull request merged**
