### PR TITLE
Add maven files for version 11 and other minor updates.

### PR DESCRIPTION
**Pull request by dinogun**

### CODE REVIEW

**Review by karianna — COMMENTED** [review]
Seems a lot of duplicated code and the maven version seems out of date a bit?

**Comment by dinogun** [comment]
@karianna The duplication was by design, we wanted the maven parts not to be in the openjdk-docker repo (See [this](https://github.com/AdoptOpenJDK/openjdk-docker/pull/52) for our earlier discussion).
I'll submit a separate PR to download and use the openjdk-docker repo scripts instead of duplicating it here, that way they don't need to be updated twice.
Mark Kempster offered to submit a PR for the maven version upgrade, will wait for him to submit.

**Comment by mkempster** [comment]
Submitted #3

**Comment by karianna** [comment]
> @karianna The duplication was by design, we wanted the maven parts not to be in the openjdk-docker repo (See [this](https://github.com/AdoptOpenJDK/openjdk-docker/pull/52) for our earlier discussion).
> I'll submit a separate PR to download and use the openjdk-docker repo scripts instead of duplicating it here, that way they don't need to be updated twice.
> Mark Kempster offered to submit a PR for the maven version upgrade, will wait for him to submit.

OK can we document that deliberate choice in the code or in our CONTRIBUTING.md?

**Comment by dinogun** [comment]
Added a README and updated all the Dockerfiles to reflect the new Maven version. @karianna Let me know if the README needs more updates. Thanks

**Comment by karianna** [comment]
LGTM but why not Maven 3.6.3?

**Comment by mkempster** [comment]
I updated to maven 3.6.0 since that mirrors the docker-official version https://github.com/carlossg/docker-maven

I'll do another PR today for mvn-3.6.3 based on the latest merged code.

**Comment by dinogun** [comment]
Agree with @mkempster. The official maven images are currently on 3.6.0

**Comment by mkempster** [comment]
> I'll do another PR today for mvn-3.6.3 based on the latest merged code.

Scratch that. Maven's latest advertised release seems to be 3.6.0. 3.6.3 doesn't seem to be available to download from the common places.

**Review by karianna — APPROVED** [review]
LGTM

**Pull request merged**
